version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  admin:
    container_name: admin
    image: ecommerce-site-main-admin
    build: 
       context: ./admin
       dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?user=root&password=1111
    depends_on:
      - db
    ports:
      - "8080:8080"  
    networks:
      - mynetwork

  user:
    container_name: user
    image: ecommerce-site-main-user
    build: 
       context: ./user
       dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?user=root&password=1111
    depends_on:
      - db
    ports:
      - "8019:8019"  
    networks:
      - mynetwork      

networks:
  mynetwork:
    driver: bridge
