# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3306:3306"

  user:
    container_name: admin
    image: ecommerce-site-main-admin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
